-- Contact messages table for /contact form
create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  topic text not null,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.contact_messages enable row level security;

-- Allow anonymous inserts from website contact form
do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'contact_messages'
      and policyname = 'Allow anon insert contact messages'
  ) then
    create policy "Allow anon insert contact messages"
      on public.contact_messages
      for insert
      to anon
      with check (true);
  end if;
end $$;

